# Generated by Django 3.2 on 2022-09-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='audio',
            field=models.TextField(null=True),
        ),
    ]
