# Generated by Django 3.2 on 2022-09-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='audio',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
