# Generated by Django 3.2 on 2022-09-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220925_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='audio',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
