# Generated by Django 3.2 on 2022-09-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
