# Generated by Django 3.2 on 2022-09-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='audio',
        ),
    ]
